title: Redteaming-juttuja
description: Tämä osio sisältää CTF-haasteita, Metaspoitablen roottailua, kryptografiaa ja erilaisia skriptejä.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
